services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Zeus8185
      MYSQL_DATABASE: db
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - .:/app
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  web:
    volumes:
      - .:/app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  mysql_data:
